stages:
  data_ingestion:

    cmd: python src/Chicken_Disease_classification/pipeline/Stage_01_Data_ingestion.py
    
    deps:
      - src/Chicken_Disease_classification/pipeline/Stage_01_Data_ingestion.py
      - config/config.yaml
  
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  prepare_base_model:

    cmd: python src/Chicken_Disease_classification/pipeline/Stage_02_Prepare_base_model.py
    
    deps:
      - src/Chicken_Disease_classification/pipeline/Stage_02_Prepare_base_model.py
      - config/config.yaml
  
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    
    outs:
      - artifacts/prepare_base_model 

  training:
  
      cmd: python src/Chicken_Disease_classification/pipeline/Stage_03_Training.py
      
      deps:
        - src/Chicken_Disease_classification/pipeline/Stage_03_Training.py
        - src/Chicken_Disease_classification/components/prepare_callbacks.py
        - config/config.yaml
        - artifacts/data_ingestion/Chicken-fecal-images
        - artifacts/prepare_base_model
    
      params:
        - IMAGE_SIZE
        - EPOCHS
        - BATCH_SIZE
        - AUGMENTATION
      
      outs:
        - artifacts/training/model.keras



  evaluation:
  
      cmd: python src/Chicken_Disease_classification/pipeline/Stage_04_Evaluation.py
      
      deps:
        - src/Chicken_Disease_classification/pipeline/Stage_04_Evaluation.py
        - config/config.yaml
        - artifacts/data_ingestion/Chicken-fecal-images
        - artifacts/training/model.keras
      
      params:
        - IMAGE_SIZE
        - BATCH_SIZE
        

      metrics:
        - scores.json:
            cache: false