AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model #https://keras.io/api/applications/vgg/
BATCH_SIZE: 16 
INCLUDE_TOP: False 
EPOCHS: 16 #Number of epochs to train the model. An epoch is one complete forward and backward pass of all the training examples.
CLASSES: 2 
WEIGHTS: imagenet #ImageNet is an image classification and localization competition.  VGG16 is a 16-layer network architecture and weights trained on the competition dataset by the Visual Geometry Group (VGG).
LEARNING_RATE: 0.01