artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kamaleshkio/CNN_Classifier/raw/refs/heads/main/data/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras #The .h5 file extension primarily indicates a file saved in the Hierarchical Data Format version 5 (HDF5), a versatile format used for storing various types of data, including scientific data, machine learning models, and more
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras #The .keras file extension is used to save Keras models in a format that is optimized for Keras, allowing for better compatibility and performance when loading and using the model within the Keras framework. 


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras

training :
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras



  