artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kamaleshkio/CNN_Classifier/raw/refs/heads/main/data/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5 #The .h5 file extension primarily indicates a file saved in the Hierarchical Data Format version 5 (HDF5), a versatile format used for storing various types of data, including scientific data, machine learning models, and more
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 
